# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  languageName: English
  contentDir: content/en
  weight: 1
  menus:
    main:
      - name: Publications
        url: publication
        weight: 100
      - name: Experience
        url: experience
        weight: 200

zh:
  languageCode: zh-Hans
  languageName: 中文
  contentDir: content/zh
  title: 余润心
  weight: 2
  params:
    description: 中国科学院城市环境研究所助理教授，研究方向为可持续人工智能、气候政策、能源低碳转型、资源与环境经济学。
  menus:
    main:
      - name: 论文
        url: publication
        weight: 100
      - name: 经历
        url: experience
        weight: 200
